# Generated by Django 5.0.6 on 2024-05-13 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodeconsulta',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tipodeconsulta',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
