# Generated by Django 5.0.6 on 2024-05-30 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0005_notadesesion_objetivodetratamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivodetratamiento',
            old_name='objetivo',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='notadesesion',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='objetivodetratamiento',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='objetivodetratamiento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='objetivodetratamiento',
            name='profesional',
        ),
        migrations.AddField(
            model_name='objetivodetratamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
